name: Build and Upload SBOM to Dependency-Track
on:
  push:
    branches:
      - '*'
jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
      
      - name: Restore .NET dependencies
        run: dotnet restore
      
      - name: Install & Generate SBOM
        run: |
          dotnet tool install --global CycloneDX
          
          # Debug: List all files to see what's available
          echo "Repository structure:"
          find . -name "*.sln" -o -name "*.csproj" -o -name "*.fsproj" -o -name "*.vbproj" | head -10
          
          # Find the solution file first, fallback to project files
          SOLUTION_FILE=$(find . -name "*.sln" | head -n 1)
          
          if [ -z "$SOLUTION_FILE" ]; then
            echo "No .sln file found, looking for project files..."
            PROJECT_FILE=$(find . -name "*.csproj" -o -name "*.fsproj" -o -name "*.vbproj" | head -n 1)
            if [ -z "$PROJECT_FILE" ]; then
              echo "No solution or project files found!"
              exit 1
            else
              echo "Found project file: $PROJECT_FILE"
              TARGET_FILE="$PROJECT_FILE"
            fi
          else
            echo "Found solution file: $SOLUTION_FILE"
            TARGET_FILE="$SOLUTION_FILE"
          fi
          
          # Create output directory
          mkdir -p ./sbom
          
          # Generate SBOM with correct syntax
          dotnet-CycloneDX "$TARGET_FILE" --output ./sbom --filename bom.xml --output-format Xml
          
          # Debug: Show what was generated
          echo "Generated SBOM files:"
          ls -la ./sbom/
          
          # Show first few lines of the BOM
          echo "First 20 lines of generated BOM:"
          head -20 ./sbom/bom.xml
      
      - name: Upload SBOM with curl (POST multipart)
        env:
          DTRACK_API_KEY: ${{ secrets.DTRACK_API_KEY }}
        run: |
          curl --fail-with-body -v -i -w "\nHTTP Status: %{http_code}\n" \
            -X POST "https://ca-dev-global-dtrack-api.whitesea-2475732e.westeurope.azurecontainerapps.io/api/v1/bom" \
            -H "X-Api-Key: $DTRACK_API_KEY" \
            -H "accept: application/json" \
            -H "Content-Type: multipart/form-data" \
            -F "autoCreate=true" \
            -F "projectName=${{ github.event.repository.name }}" \
            -F "projectVersion=${{ github.ref_name }}" \
            -F "bom=@./sbom/bom.xml"
